Demux unaligned CRAM with FASTQ output - CW-6447

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -63,6 +63,7 @@ docker-run:
                 "output_bam",
                 "polya_tails",
                 "demux",
+                "demux_fastq_unalign",
                 "duplex_demux",
                 "demux-align"
             ]
@@ -157,6 +158,24 @@ docker-run:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-basecalling/wf-basecalling-demux-demo.tar.gz && tar -xzvf demo_data.tar.gz && cat wf-basecalling-demux-demo/README && rm demo_data.tar.gz"
              NF_WORKFLOW_OPTS: "--input wf-basecalling-demux-demo/input --barcode_kit SQK-RBK114-96 --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v5.0.0 ${NF_PROCESS_OPTIONS}"
              NF_IGNORE_PROCESSES: "output_pod5s,pair_stats,progressive_pairings,split_xam,stopCondition,cram_cache"
+        - if: $MATRIX_NAME == "demux_fastq_unalign"
+          variables:
+             NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-basecalling/wf-basecalling-demux-demo.tar.gz && tar -xzvf demo_data.tar.gz && cat wf-basecalling-demux-demo/README && rm demo_data.tar.gz"
+             NF_WORKFLOW_OPTS: "--input wf-basecalling-demux-demo/input --barcode_kit SQK-RBK114-96 --output_fmt fastq --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v5.0.0 ${NF_PROCESS_OPTIONS}"
+             NF_IGNORE_PROCESSES: "output_pod5s,pair_stats,progressive_pairings,split_xam,stopCondition,cram_cache"
+             AFTER_NEXTFLOW_CMD: |
+              MISSING_FILES=();
+              for BARCODE in barcode{01..96}; do
+                FILE=wf-basecalling/demuxed/demuxed/26cdc4c3-c4ca-49a7-a167-8679dace0e2d_SQK-RBK114-96_$${BARCODE}/reads.fastq;
+                [ -f $${FILE} ] || MISSING_FILES+=("$${FILE}");
+              done;
+              if [ $${#MISSING_FILES[@]} -ne 0 ]; then
+                echo "Missing expected demuxed fastq files:";
+                for FILE in "$${MISSING_FILES[@]}"; do
+                  echo -e "\t$${FILE}";
+                done;
+                exit 1;
+              fi
         - if: $MATRIX_NAME == "demux-align"
           variables:
              NF_BEFORE_SCRIPT: "wget -qO demo_data.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-basecalling/wf-basecalling-demux-demo.tar.gz && \
